### ISSUE TITLE
Character got stuck

### ISSUE THREAD

**Issue by Colgateinuntap** [crawl/qw#1]
https://underhound.eu/crawl/morgue/Colgate/morgue-Colgate-20210824-060326.txt It ended up in room with stairs up and escape hatch down and got stuck.

**Comment by gammafunk** [comment]
qw has greatly improved goal planning and level pathing as of [version 0.2](https://github.com/crawl/qw/releases/tag/0.2.0) and doesn't get stuck in common situations like this any longer, hence I'm closing this issue. Feel free to give it a try with crawl 0.31 or 0.30, although you'll need to run it locally or on your own WebTiles server.

qw does still have some far less common cases where it gets stuck as a result of bugs in its travel system. Please feel free to report those if you see them in the current version, thanks!
